version: 3

tasks:
  build:
    cmd: bun scripts/build.js
    desc: Build JSON Schemas
    sources:
      - schemas/*.yaml
    generates:
      - docs/*.schema.json
  lint:
    deps:
      - build
    cmd: bun ajv compile -s 'docs/*.schema.json' --spec=draft2020 --strict-types -c ajv-formats
    sources:
      - docs/*.schema.json
    generates:
      - docs/*.schema.json
  validate:
    deps:
      - build
    cmd: bun ajv compile -s 'docs/*.schema.json' --spec=draft2020 --strict=true --all-errors -c ajv-formats
    sources:
      - docs/*.schema.json
    generates:
      - docs/*.schema.json
  format:
    deps:
      - build
    cmd: bun prettier --write 'docs/*' 'schemas/*'
    sources:
      - docs/*
      - schemas/*
    generates:
      - docs/*
      - schemas/*
  test:
    deps:
      - build
    cmd: bun scripts/test.js
    sources:
      - docs/*.schema.json
